const BASE_URL = (process.env.NETSHOP_API_URL || "https://www.netshop.co.mz/api/v1").replace(/\/+$/, "");
function config(){return {apiKey:process.env.NETSHOP_API_KEY||"",walletId:process.env.NETSHOP_WALLET_ID||""};}
function normalizeMethod(method){const value=String(method||"").toLowerCase().trim();if(["m-pesa","m_pesa"].includes(value))return"mpesa";if(["e-mola","e_mola"].includes(value))return"emola";if(["m-kesh","m_kesh","m kesh"].includes(value))return"mkesh";if(["visa","mastercard","cartao","cartão"].includes(value))return"card";return value;}
function normalizePhone(phone){let value=String(phone||"").replace(/\s+/g,"").replace(/[^\d+]/g,"");if(value.startsWith("+"))value=value.slice(1);if(!value.startsWith("258"))value=`258${value}`;if(!/^2588\d{8}$/.test(value))throw new Error("Número de telefone inválido.");return`+${value}`;}
function assertConfigured(){const{apiKey,walletId}=config();if(!apiKey)throw Object.assign(new Error("NETSHOP_API_KEY não configurada."),{code:"PROVIDER_NOT_CONFIGURED",provider:"netshop",retryable:false});if(!walletId)throw Object.assign(new Error("NETSHOP_WALLET_ID não configurada."),{code:"PROVIDER_NOT_CONFIGURED",provider:"netshop",retryable:false});}
async function request(path,options={}){assertConfigured();const{apiKey,walletId}=config();const response=await fetch(`${BASE_URL}/${String(path).replace(/^\/+/,"")}`,{...options,headers:{Authorization:`Bearer ${apiKey}`,"X-Wallet-ID":String(walletId),Accept:"application/json","Content-Type":"application/json",...(options.headers||{})},signal:options.signal||AbortSignal.timeout(30000)});const text=await response.text();let data={};try{data=text?JSON.parse(text):{};}catch{throw Object.assign(new Error(`Resposta inválida do NetShop (HTTP ${response.status}).`),{provider:"netshop",status:response.status,retryable:false});}if(!response.ok)throw Object.assign(new Error(data?.error?.message||data?.message||`NetShop HTTP ${response.status}`),{provider:"netshop",status:response.status,code:data?.error?.code||data?.code||null,retryable:false,providerResponse:data});return data;}
export async function health(){try{assertConfigured();return{provider:"netshop",configured:true,healthy:true};}catch(error){return{provider:"netshop",configured:false,healthy:false,error:error.message};}}
export async function createCharge({amount,method,phone,reference,customerName}){const normalizedMethod=normalizeMethod(method);const payload={amount:Number(amount),currency:"MZN",method:normalizedMethod,...(phone?{msisdn:normalizePhone(phone)}:{}),reference:String(reference||`PAYGO-${Date.now()}`),...(customerName?{customer_name:String(customerName).slice(0,160)}:{})};const response=await request("/charges",{method:"POST",headers:{"Idempotency-Key":payload.reference},body:JSON.stringify(payload)});const data=response?.data||response;return{success:true,provider:"netshop",paymentId:data?.id||data?.payment_id||null,reference:data?.reference||payload.reference,status:data?.status||"pending",amount:Number(data?.amount??amount),method:normalizedMethod,checkoutUrl:data?.checkout_url||data?.checkoutUrl||null,raw:response};}
export default{health,createCharge};
