(()=>{
const pages={
'dashboard.html':['Dashboard','layout-dashboard','Principal'],'relatorios.html':['Relatórios','bar-chart-3','Principal'],'clientes.html':['Clientes','users','Operações'],'pedidos.html':['Pedidos','shopping-bag','Operações'],'payout.html':['Payouts','send','Operações'],'cartoes.html':['Cartões','credit-card','Operações'],'gerar-fatura.html':['Faturas','file-text','Operações'],'afiliados.html':['Afiliados','users-round','Ecossistema'],'candidaturas.html':['Candidaturas','badge-check','Ecossistema'],'logs.html':['Transações & Logs','activity','Ecossistema'],'logs-admin.html':['Auditoria Admin','shield-check','Ecossistema'],'configuracoes.html':['Configurações','settings','Sistema'],'admin.html':['Administradores','user-cog','Sistema'],'mensagem.html':['Mensagens','message-square','Ecossistema']};
const groups=['Principal','Operações','Ecossistema','Sistema'];
const labels={Principal:['dashboard.html','relatorios.html'],Operações:['clientes.html','pedidos.html','payout.html','cartoes.html','gerar-fatura.html'],Ecossistema:['afiliados.html','candidaturas.html','logs.html','logs-admin.html','mensagem.html'],Sistema:['configuracoes.html','admin.html']};
const file=location.pathname.split('/').pop()||'dashboard.html';
const icon=n=>`<i data-lucide="${n}"></i>`;
function ensureTheme(){if(document.querySelector('link[data-paygo-admin-theme]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='admin-theme.css';l.dataset.paygoAdminTheme='true';document.head.appendChild(l)}
function shell(){
 ensureTheme();const old=document.querySelector('aside');
 if(old){let nav='';groups.forEach(g=>{nav+=`<div class="pg-label">${g}</div>`;labels[g].forEach(p=>{const d=pages[p];nav+=`<a class="pg-item ${p===file?'active':''}" href="${p}">${icon(d[1])}<span>${d[0]}</span></a>`})});const a=document.createElement('aside');a.id='sidebar';a.className='pg-sidebar';a.innerHTML=`<div class="pg-brand"><div class="pg-brand-mark">⚡</div><div><div class="pg-brand-title">PayGo</div><div class="pg-brand-sub">Admin Financeiro</div></div></div><nav class="pg-nav">${nav}</nav><div class="pg-footer"><a class="pg-item" href="../index.html">${icon('arrow-left')}<span>Voltar ao PayGo</span></a></div>`;old.replaceWith(a)}
 const main=document.querySelector('main');if(main)main.classList.add('pg-main');
 let overlay=document.getElementById('pgOverlay');if(!overlay){overlay=document.createElement('div');overlay.id='pgOverlay';overlay.className='pg-overlay';document.body.prepend(overlay)}
 let menu=document.getElementById('menu');if(!menu){menu=document.createElement('button');menu.id='menu';menu.className='pg-menu';menu.innerHTML=icon('menu');const h=document.querySelector('header');if(h)h.prepend(menu)}
 const sidebar=document.getElementById('sidebar');menu.onclick=()=>{sidebar?.classList.add('open');overlay.classList.add('open')};overlay.onclick=()=>{sidebar?.classList.remove('open');overlay.classList.remove('open')};
 if(window.lucide)lucide.createIcons();
 if(file==='configuracoes.html')setTimeout(settingsCenter,80);
}
function settingsCenter(){
 if(document.getElementById('paygoSettingsCenter'))return;const main=document.querySelector('main');if(!main)return;
 const style=document.createElement('style');style.id='paygoSettingsCenterCss';style.textContent=`
 #paygoSettingsCenter{--n:#06142e;--n2:#123b63;--bg:#f3f6fb;--line:#e3e9f2;--text:#101a2f;--muted:#69788d;--blue:#2563eb;--green:#159a78;--amber:#d88a08;--red:#dc3d4b;color:var(--text)}
 #paygoSettingsCenter .sc-hero{background:linear-gradient(135deg,#06142e,#0d2b4d 62%,#123b63);color:#fff;border-radius:28px;padding:28px;position:relative;overflow:hidden;box-shadow:0 18px 45px rgba(15,23,42,.13)}
 #paygoSettingsCenter .sc-hero:after{content:"";position:absolute;width:420px;height:420px;border-radius:50%;right:-170px;top:-245px;background:rgba(56,189,248,.11)}
 #paygoSettingsCenter .sc-kicker{display:inline-flex;gap:8px;align-items:center;padding:8px 13px;border-radius:999px;background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.12);font-size:11px;font-weight:900;letter-spacing:.14em;text-transform:uppercase}
 #paygoSettingsCenter h1{font-size:clamp(28px,4vw,42px);line-height:1.08;font-weight:900;letter-spacing:-.03em;margin:18px 0 8px;color:#fff}#paygoSettingsCenter .sc-hero p{color:#c8d7ea;max-width:760px;line-height:1.6;margin:0}
 #paygoSettingsCenter .sc-grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:18px;margin-top:18px}.sc-card{grid-column:span 6;background:#fff;border:1px solid #e3e9f2;border-radius:22px;padding:22px;box-shadow:0 14px 38px rgba(15,23,42,.065)}.sc-card.wide{grid-column:span 8}.sc-card.third{grid-column:span 4}
 #paygoSettingsCenter .sc-title{display:flex;align-items:center;gap:12px;margin-bottom:17px}.sc-title>div{width:40px;height:40px;border-radius:13px;background:#edf4ff;color:#2563eb;display:grid;place-items:center}.sc-title h2{margin:0;font-size:18px;font-weight:900}.sc-sub{font-size:12px;color:#69788d;margin-top:3px}
 #paygoSettingsCenter .sc-row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.sc-field{margin-top:13px}.sc-field label{display:block;font-size:12px;font-weight:800;margin-bottom:7px;color:#344256}.sc-field input,.sc-field select{width:100%;min-height:46px;padding:10px 13px;border:1px solid #d6e0ec;border-radius:13px;background:#fff;color:#101a2f;font:inherit;outline:0}.sc-field input:focus,.sc-field select:focus{border-color:#60a5fa;box-shadow:0 0 0 4px rgba(37,99,235,.1)}.sc-help{font-size:11px;color:#69788d;margin-top:5px;line-height:1.5}
 #paygoSettingsCenter .sc-status{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:13px 0;border-top:1px solid #e3e9f2}.sc-status:first-of-type{border-top:0}.sc-status strong{font-size:13px}.sc-status small{display:block;color:#69788d;margin-top:3px}.sc-pill{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:7px 10px;font-size:10px;font-weight:900;text-transform:uppercase;white-space:nowrap}.sc-ok{background:#e5f8f1;color:#12815f}.sc-info{background:#e6f0ff;color:#1d5bc1}.sc-warn{background:#fff4d7;color:#a86b00}.sc-off{background:#ffe5e7;color:#b4232e}
 #paygoSettingsCenter .sc-wallet{background:linear-gradient(135deg,#06142e,#123158);color:#fff;border-radius:22px;padding:20px;position:relative;overflow:hidden}.sc-wallet:after{content:"";position:absolute;width:210px;height:210px;border-radius:50%;right:-100px;top:-100px;background:rgba(96,165,250,.1)}.sc-wallet>*{position:relative;z-index:1}.sc-balance{font-size:30px;font-weight:900;margin-top:7px}.sc-muted{color:#b9c9dd}.sc-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}
 #paygoSettingsCenter .sc-toggle{display:flex;align-items:center;justify-content:space-between;gap:12px;border:1px solid #e3e9f2;border-radius:14px;padding:13px;margin-top:10px}.sc-toggle input{width:20px;height:20px;accent-color:#2563eb}.sc-btn{border:0;border-radius:13px;padding:11px 15px;font-weight:900;font-size:12px;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:7px}.sc-primary{background:#2563eb;color:#fff}.sc-light{background:#edf4ff;color:#174ea6}.sc-white{background:rgba(255,255,255,.1);color:#fff;border:1px solid rgba(255,255,255,.12)}
 #paygoSettingsCenter .sc-save{position:sticky;bottom:12px;z-index:20;background:rgba(255,255,255,.95);backdrop-filter:blur(14px);border:1px solid #e3e9f2;border-radius:18px;padding:12px 14px;margin-top:18px;display:flex;align-items:center;justify-content:space-between;gap:12px;box-shadow:0 15px 35px rgba(15,23,42,.12)}.sc-note{font-size:11px;color:#69788d}
 @media(max-width:1100px){#paygoSettingsCenter .sc-card,#paygoSettingsCenter .sc-card.wide,#paygoSettingsCenter .sc-card.third{grid-column:span 12}}@media(max-width:650px){#paygoSettingsCenter .sc-row{grid-template-columns:1fr}#paygoSettingsCenter .sc-card{padding:18px}.sc-save{flex-direction:column;align-items:stretch}.sc-save .sc-btn{width:100%}}
 `;document.head.appendChild(style);
 const oldForm=document.getElementById('settingsForm');if(oldForm)oldForm.style.display='none';main.querySelectorAll('.hero-card').forEach(e=>e.style.display='none');
 const box=document.createElement('div');box.id='paygoSettingsCenter';box.innerHTML=`
 <section class="sc-hero"><div class="sc-kicker">${icon('shield-check')} Centro de configuração PayGo OS</div><h1>Configurações</h1><p>Identidade, pagamentos, carteiras, segurança, equipa, notificações, afiliados e estado técnico da plataforma num único espaço.</p><div style="display:flex;gap:8px;margin-top:18px;flex-wrap:wrap"><span class="sc-pill sc-info">Produção</span><span id="scSync" class="sc-pill sc-ok">Sincronizado</span></div></section>
 <form id="scForm"><div class="sc-grid">
 <section class="sc-card wide"><div class="sc-title"><div>${icon('building-2')}</div><div><h2>Geral</h2><div class="sc-sub">Identidade e comportamento público.</div></div></div><div class="sc-row"><div class="sc-field"><label>Nome da plataforma</label><input id="scName"></div><div class="sc-field"><label>Logo (URL)</label><input id="scLogo" placeholder="https://..."></div></div><div class="sc-row"><div class="sc-field"><label>Email de suporte</label><input id="scEmail" type="email"></div><div class="sc-field"><label>Telefone / WhatsApp</label><input id="scPhone"></div></div><div class="sc-row"><div class="sc-field"><label>Moeda padrão</label><select id="scCurrency"><option>MZN</option><option>USD</option><option>EUR</option></select></div><div class="sc-field"><label>Fuso horário</label><select id="scTimezone"><option>Africa/Maputo</option><option>Africa/Johannesburg</option><option>UTC</option></select></div></div><div class="sc-toggle"><div><strong>Manutenção da plataforma</strong><div class="sc-help">Apenas Super Admin pode ativar.</div></div><input id="scMaintenance" type="checkbox"></div></section>
 <section class="sc-card third"><div class="sc-title"><div>${icon('activity')}</div><div><h2>Estado</h2><div class="sc-sub">Serviços do PayGo OS.</div></div></div><div class="sc-status"><div><strong>Firebase</strong><small>Auth + Firestore</small></div><span class="sc-pill sc-ok">Conectado</span></div><div class="sc-status"><div><strong>ZumboPay</strong><small>Gateway principal</small></div><span id="scZp" class="sc-pill sc-ok">Configurado</span></div><div class="sc-status"><div><strong>Secrets</strong><small>Vercel Environment</small></div><span class="sc-pill sc-info">Seguro</span></div><div class="sc-status"><div><strong>PayGo OS</strong><small>Admin console</small></div><span class="sc-pill sc-info">v3.0</span></div><div class="sc-status"><div><strong>Última sincronização</strong><small id="scLast">—</small></div><span class="sc-pill sc-ok">Ativo</span></div></section>
 <section class="sc-card wide"><div class="sc-title"><div>${icon('wallet')}</div><div><h2>Pagamentos</h2><div class="sc-sub">ZumboPay é o gateway principal para M-Pesa, e-Mola e B2C.</div></div></div><div class="sc-wallet"><strong>ZumboPay</strong><div class="sc-muted">Gateway principal · sem API keys expostas no painel</div><div class="sc-actions"><button type="button" id="scTest" class="sc-btn sc-white">${icon('plug')} Testar conexão</button><button type="button" id="scVerify" class="sc-btn sc-white">${icon('wallet-cards')} Verificar wallet</button></div></div><div class="sc-row"><div class="sc-field"><label>Taxa de payout (MT)</label><input id="scFee" type="number" min="0" step="0.01"></div><div class="sc-field"><label>Limite mínimo B2C (MT)</label><input id="scMin" type="number" min="0" step="0.01"></div></div><div class="sc-row"><div class="sc-field"><label>Limite máximo B2C (MT)</label><input id="scMax" type="number" min="0" step="0.01"></div><div class="sc-field"><label>Merchant ID</label><input id="scMerchant" placeholder="Configurado nas variáveis da Vercel" disabled></div></div></section>
 <section class="sc-card third"><div class="sc-title"><div>${icon('landmark')}</div><div><h2>Carteiras & Payout</h2><div class="sc-sub">Dados operacionais.</div></div></div><div class="sc-field"><label>Wallet operacional</label><input id="scWalletName" placeholder="PayGoVD"></div><div class="sc-field"><label>Wallet UUID</label><input id="scWalletUuid" placeholder="UUID da wallet"></div><div class="sc-wallet" style="margin-top:14px"><div class="sc-muted">Saldo disponível</div><div id="scBalance" class="sc-balance">—</div></div><div class="sc-toggle"><div><strong>Confirmar antes de enviar</strong><div class="sc-help">Protege o fluxo B2C.</div></div><input id="scConfirm" type="checkbox" checked></div><div class="sc-status"><div><strong>Histórico</strong><small>Payouts persistentes</small></div><a class="sc-btn sc-light" href="payout.html">Abrir</a></div></section>
 <section class="sc-card"><div class="sc-title"><div>${icon('shield')}</div><div><h2>Segurança</h2><div class="sc-sub">Políticas administrativas.</div></div></div><div class="sc-row"><div class="sc-field"><label>Timeout (min)</label><input id="scTimeout" type="number" min="5"></div><div class="sc-field"><label>IPs autorizados</label><input id="scIps" placeholder="Opcional"></div></div><div class="sc-toggle"><div><strong>2FA obrigatório</strong><div class="sc-help">Preferência administrativa.</div></div><input id="sc2fa" type="checkbox"></div><div class="sc-toggle"><div><strong>Logs de segurança</strong></div><input id="scLogs" type="checkbox" checked></div></section>
 <section class="sc-card"><div class="sc-title"><div>${icon('users-round')}</div><div><h2>Equipa & Permissões</h2><div class="sc-sub">Controlo de acesso.</div></div></div><div class="sc-status"><div><strong>Administradores</strong><small>Roles e permissões</small></div><a class="sc-btn sc-light" href="admin.html">Gerir equipa</a></div><div class="sc-field"><label>Role padrão</label><select id="scRole"><option>admin</option><option>support</option><option>finance</option></select></div><div class="sc-toggle"><div><strong>Convites ativos</strong></div><input id="scInvites" type="checkbox" checked></div><div class="sc-toggle"><div><strong>Desativar inativos</strong></div><input id="scInactive" type="checkbox"></div></section>
 <section class="sc-card"><div class="sc-title"><div>${icon('bell')}</div><div><h2>Notificações</h2><div class="sc-sub">Alertas operacionais.</div></div></div><div class="sc-toggle"><div><strong>Email</strong></div><input id="scNEmail" type="checkbox" checked></div><div class="sc-toggle"><div><strong>WhatsApp</strong></div><input id="scNWhatsapp" type="checkbox" checked></div><div class="sc-toggle"><div><strong>Alertas de payout</strong></div><input id="scNPayout" type="checkbox" checked></div><div class="sc-toggle"><div><strong>Falhas de pagamento</strong></div><input id="scNPayment" type="checkbox" checked></div><div class="sc-toggle"><div><strong>KYC/KYB</strong></div><input id="scNKyc" type="checkbox" checked></div><div class="sc-toggle"><div><strong>Saldo baixo</strong></div><input id="scNLow" type="checkbox" checked></div></section>
 <section class="sc-card"><div class="sc-title"><div>${icon('network')}</div><div><h2>Afiliados</h2><div class="sc-sub">Comissões e regras.</div></div></div><div class="sc-row"><div class="sc-field"><label>Comissão padrão (%)</label><input id="scAComm" type="number" min="0" step="0.1"></div><div class="sc-field"><label>Bónus padrão (MT)</label><input id="scABonus" type="number" min="0" step="0.01"></div></div><div class="sc-field"><label>Regra de pagamento</label><select id="scARule"><option value="monthly">Mensal</option><option value="weekly">Semanal</option><option value="threshold">Por limite</option></select></div><div class="sc-toggle"><div><strong>Programa ativo</strong></div><input id="scAActive" type="checkbox" checked></div></section>
 <section class="sc-card"><div class="sc-title"><div>${icon('server-cog')}</div><div><h2>Sistema</h2><div class="sc-sub">Infraestrutura e ambiente.</div></div></div><div class="sc-status"><div><strong>Firebase</strong><small>Auth + Firestore</small></div><span class="sc-pill sc-ok">Conectado</span></div><div class="sc-status"><div><strong>ZumboPay</strong><small>Secrets mantidos no ambiente</small></div><span class="sc-pill sc-ok">Seguro</span></div><div class="sc-status"><div><strong>API keys / secrets</strong><small>Não editáveis nesta página</small></div><span class="sc-pill sc-info">Vercel Env</span></div><div class="sc-status"><div><strong>Versão</strong><small>Admin console</small></div><span class="sc-pill sc-info">v3.0</span></div></section>
 </div><div class="sc-save"><span id="scNote" class="sc-note">As alterações ficam pendentes até guardar.</span><button class="sc-btn sc-primary" type="submit" id="scSave">${icon('save')} Guardar configurações</button></div></form>`;
 main.prepend(box);if(window.lucide)lucide.createIcons({root:box});initSettings();
}
async function initSettings(){
 const cfg={apiKey:'AIzaSyAHxyX5e9O8qQo6Z3VHURgVXhxbxSp0Qh8',authDomain:'paygo-14311.firebaseapp.com',projectId:'paygo-14311',storageBucket:'paygo-14311.firebasestorage.app',messagingSenderId:'208360646277',appId:'1:208360646277:web:aecc57cc0077ae48a52bec'};
 try{const A=await import('https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js'),Au=await import('https://www.gstatic.com/firebasejs/10.7.1/firebase-auth.js'),F=await import('https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js');const app=A.getApps().length?A.getApp():A.initializeApp(cfg);const auth=Au.getAuth(app),db=F.getFirestore(app,'paygodb');let admin=null;Au.onAuthStateChanged(auth,async u=>{if(!u)return;const us=await F.getDoc(F.doc(db,'users',u.uid));if(!us.exists()||!['admin','superadmin'].includes(us.data().role))return;admin={u,role:us.data().role};const s=await F.getDoc(F.doc(db,'settings','global'));fill(s.exists()?s.data():{});});
 document.getElementById('scForm').addEventListener('submit',async e=>{e.preventDefault();if(!admin)return alert('Sessão administrativa ainda não carregada.');if(document.getElementById('scMaintenance').checked&&admin.role!=='superadmin')return alert('Apenas o Super Admin pode ativar a manutenção.');const b=document.getElementById('scSave');b.disabled=true;const v=collect();try{await F.setDoc(F.doc(db,'settings','global'),{...v,paymentGateway:'zumbopay',paysuiteActive:false,updatedAt:F.serverTimestamp(),updatedBy:admin.u.uid,resendApiKey:F.deleteField(),larkWebhook:F.deleteField()},{merge:true});document.getElementById('scNote').textContent='Guardado com sucesso · '+new Date().toLocaleString('pt-MZ');document.getElementById('scSync').textContent='Sincronizado';}catch(err){console.error(err);alert('Erro ao guardar configurações.');}finally{b.disabled=false;}});
 document.getElementById('scTest').onclick=async()=>{const b=document.getElementById('scTest');b.disabled=true;b.textContent='A verificar...';try{const r=await fetch('/api/admin/zumbopay/payout',{method:'OPTIONS'});document.getElementById('scZp').textContent=r.ok?'Disponível':'Backend disponível';}catch(e){document.getElementById('scZp').textContent='Verificar backend';document.getElementById('scZp').className='sc-pill sc-warn';}finally{b.disabled=false;b.innerHTML=`${icon('plug')} Testar conexão`;if(window.lucide)lucide.createIcons({root:b});}};
 document.getElementById('scVerify').onclick=async()=>{const b=document.getElementById('scVerify');b.disabled=true;b.textContent='A verificar...';try{const r=await fetch('/api/admin/zumbopay/payout',{method:'GET',headers:{Authorization:'Bearer '+await admin.u.getIdToken()}});const d=await r.json().catch(()=>({}));document.getElementById('scBalance').textContent=r.ok&&d.balance!=null?Number(d.balance).toLocaleString('pt-MZ',{minimumFractionDigits:2})+' MT':r.ok?'Configurada':'Não verificada';document.getElementById('scZp').textContent=r.ok?'Conectado':'Verificar backend';}catch(e){document.getElementById('scBalance').textContent='Não verificado';}finally{b.disabled=false;b.innerHTML=`${icon('wallet-cards')} Verificar wallet`;if(window.lucide)lucide.createIcons({root:b});}};
 }catch(e){console.error('settings center',e)}
}
function fill(s){const m={scName:['platformName','PayGo'],scLogo:['logoUrl',''],scEmail:['supportEmail','suporte@paygo.co.mz'],scPhone:['supportPhone','258877522255'],scCurrency:['currency','MZN'],scTimezone:['timezone','Africa/Maputo'],scFee:['payoutFee',0],scMin:['payoutMin',10],scMax:['payoutMax',50000],scWalletName:['walletName',''],scWalletUuid:['walletUuid',''],scConfirm:['payoutConfirmationRequired',true],scTimeout:['sessionTimeout',60],scIps:['allowedIps',''],sc2fa:['twoFactorRequired',false],scLogs:['securityLogs',true],scRole:['defaultAdminRole','admin'],scInvites:['adminInvitesEnabled',true],scInactive:['disableInactiveAdmins',false],scNEmail:['notifyEmail',true],scNWhatsapp:['notifyWhatsapp',true],scNPayout:['notifyPayout',true],scNPayment:['notifyPayment',true],scNKyc:['notifyKyc',true],scNLow:['notifyLowBalance',true],scAComm:['affiliateCommission',3],scABonus:['affiliateBonus',0],scARule:['affiliatePaymentRule','monthly'],scAActive:['affiliateProgramActive',true],scMaintenance:['isMaintenanceMode',false]};Object.entries(m).forEach(([id,[k,d]])=>{const e=document.getElementById(id);if(!e)return;const v=s[k]??d;if(e.type==='checkbox')e.checked=!!v;else e.value=v;});if(s.updatedAt?.toDate)document.getElementById('scLast').textContent=s.updatedAt.toDate().toLocaleString('pt-MZ');}
function collect(){const g=id=>document.getElementById(id),v=id=>g(id)?.value??'',n=id=>Number(v(id))||0,c=id=>!!g(id)?.checked;return{platformName:v('scName'),logoUrl:v('scLogo'),supportEmail:v('scEmail'),supportPhone:v('scPhone'),currency:v('scCurrency'),timezone:v('scTimezone'),isMaintenanceMode:c('scMaintenance'),payoutFee:n('scFee'),payoutMin:n('scMin'),payoutMax:n('scMax'),walletName:v('scWalletName'),walletUuid:v('scWalletUuid'),payoutConfirmationRequired:c('scConfirm'),sessionTimeout:n('scTimeout'),allowedIps:v('scIps'),twoFactorRequired:c('sc2fa'),securityLogs:c('scLogs'),defaultAdminRole:v('scRole'),adminInvitesEnabled:c('scInvites'),disableInactiveAdmins:c('scInactive'),notifyEmail:c('scNEmail'),notifyWhatsapp:c('scNWhatsapp'),notifyPayout:c('scNPayout'),notifyPayment:c('scNPayment'),notifyKyc:c('scNKyc'),notifyLowBalance:c('scNLow'),affiliateCommission:n('scAComm'),affiliateBonus:n('scABonus'),affiliatePaymentRule:v('scARule'),affiliateProgramActive:c('scAActive')};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',shell);else shell();
})();