(()=>{
const pages={
'dashboard.html':['Dashboard','layout-dashboard','Principal'],'relatorios.html':['Relatórios','bar-chart-3','Principal'],'clientes.html':['Clientes','users','Operações'],'pedidos.html':['Pedidos','shopping-bag','Operações'],'payout.html':['Payouts','send','Operações'],'cartoes.html':['Cartões','credit-card','Operações'],'gerar-fatura.html':['Faturas','file-text','Operações'],'afiliados.html':['Afiliados','users-round','Ecossistema'],'candidaturas.html':['Candidaturas','badge-check','Ecossistema'],'logs.html':['Transações & Logs','activity','Ecossistema'],'logs-admin.html':['Auditoria Admin','shield-check','Ecossistema'],'mensagem.html':['Mensagens','message-square','Ecossistema'],'configuracoes.html':['Configurações','settings','Sistema'],'admin.html':['Administradores','user-cog','Sistema']};
const groups=['Principal','Operações','Ecossistema','Sistema'];
const labels={Principal:['dashboard.html','relatorios.html'],Operações:['clientes.html','pedidos.html','payout.html','cartoes.html','gerar-fatura.html'],Ecossistema:['afiliados.html','candidaturas.html','logs.html','logs-admin.html','mensagem.html'],Sistema:['configuracoes.html','admin.html']};
const file=location.pathname.split('/').pop()||'dashboard.html';
const icon=n=>`<i data-lucide="${n}" aria-hidden="true"></i>`;
function ensureTheme(){if(document.querySelector('link[data-paygo-admin-theme]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='admin-theme.css';l.dataset.paygoAdminTheme='true';document.head.appendChild(l)}
function closeMenu(){document.getElementById('sidebar')?.classList.remove('open');document.getElementById('pgOverlay')?.classList.remove('open');document.body.classList.remove('pg-menu-open')}
function buildSidebar(){
 let nav='';groups.forEach(g=>{nav+=`<div class="pg-label">${g}</div>`;labels[g].forEach(p=>{const d=pages[p];nav+=`<a class="pg-item ${p===file?'active':''}" href="${p}">${icon(d[1])}<span>${d[0]}</span></a>`})});
 const old=document.getElementById('sidebar')||document.querySelector('aside.sidebar');
 const a=document.createElement('aside');a.id='sidebar';a.className='pg-sidebar';a.setAttribute('aria-label','Navegação administrativa');a.innerHTML=`<div class="pg-brand"><div class="pg-brand-mark">⚡</div><div><div class="pg-brand-title">PayGo</div><div class="pg-brand-sub">Admin Financeiro</div></div><button id="pgClose" class="pg-close" type="button" aria-label="Fechar menu">${icon('x')}</button></div><nav class="pg-nav">${nav}</nav><div class="pg-footer"><a class="pg-item" href="../index.html">${icon('arrow-left')}<span>Voltar ao PayGo</span></a></div>`;
 if(old)old.replaceWith(a);else document.body.prepend(a);
}
function buildMobileHeader(){
 document.querySelectorAll('#mobileMenuBtn,.mobile-menu-btn,#closeSidebarBtn,#sidebarOverlay').forEach(e=>e.remove());
 document.querySelectorAll('header button[data-menu],header button[aria-label*="menu" i]').forEach(e=>{if(e.id!=='menu')e.remove()});
 let overlay=document.getElementById('pgOverlay');if(!overlay){overlay=document.createElement('div');overlay.id='pgOverlay';overlay.className='pg-overlay';document.body.appendChild(overlay)}
 let menu=document.getElementById('menu');if(!menu){menu=document.createElement('button');menu.id='menu';menu.className='pg-menu';menu.type='button';menu.setAttribute('aria-label','Abrir menu');menu.innerHTML=icon('menu');const h=document.querySelector('header');if(h)h.prepend(menu);else document.body.prepend(menu)}
 menu.onclick=()=>{document.getElementById('sidebar')?.classList.add('open');overlay.classList.add('open');document.body.classList.add('pg-menu-open')};overlay.onclick=closeMenu;document.getElementById('pgClose')?.addEventListener('click',closeMenu);document.querySelectorAll('#sidebar a').forEach(a=>a.addEventListener('click',closeMenu));
}
function normalizeLayout(){
 const main=document.querySelector('main');if(main)main.classList.add('pg-main');
 document.body.classList.add('pg-admin-page');
 document.querySelectorAll('.fixed.inset-0.bg-grid,.fixed.top-0.left-1\/2').forEach(e=>e.classList.add('pg-legacy-decoration'));
 document.querySelectorAll('#sidebarOverlay').forEach(e=>e.remove());
}
async function settingsCenter(){
 if(file!=='configuracoes.html'||document.getElementById('paygoSettingsCenter'))return;const main=document.querySelector('main');if(!main)return;
 const oldForm=document.getElementById('settingsForm');if(oldForm)oldForm.style.display='none';
 const box=document.createElement('div');box.id='paygoSettingsCenter';box.innerHTML=`<section class="sc-hero"><span class="sc-kicker">${icon('shield-check')} PayGo OS · Centro de configuração</span><h1>Configurações</h1><p>Governe identidade, pagamentos, carteiras, segurança, equipa, notificações, afiliados e infraestrutura num único centro.</p><div class="sc-status-row"><span class="sc-pill info">Produção</span><span id="scSync" class="sc-pill ok">Sincronizado</span></div></section><form id="scForm"><div class="sc-grid">
<section class="sc-card wide"><h2>${icon('building-2')} Geral</h2><div class="sc-fields"><label>Nome da plataforma<input id="scName"></label><label>Logo URL<input id="scLogo"></label><label>Email de suporte<input id="scEmail" type="email"></label><label>Telefone / WhatsApp<input id="scPhone"></label><label>Moeda padrão<select id="scCurrency"><option>MZN</option><option>USD</option><option>EUR</option></select></label><label>Fuso horário<select id="scTimezone"><option>Africa/Maputo</option><option>Africa/Johannesburg</option><option>UTC</option></select></label></div><label class="sc-toggle">Manutenção da plataforma<input id="scMaintenance" type="checkbox"></label></section>
<section class="sc-card"><h2>${icon('activity')} Estado das integrações</h2><div class="sc-status-line"><span>Firebase<small>Auth + Firestore</small></span><b class="sc-pill ok">Conectado</b></div><div class="sc-status-line"><span>ZumboPay<small>Gateway principal</small></span><b id="scZp" class="sc-pill ok">Conectado</b></div><div class="sc-status-line"><span>Merchant<small>Configuração</small></span><b class="sc-pill info">Configurado</b></div><div class="sc-status-line"><span>Wallet<small>Operacional</small></span><b id="scWalletState" class="sc-pill info">Configurada</b></div><div class="sc-status-line"><span>Secrets<small>Vercel Environment</small></span><b class="sc-pill info">Seguro</b></div><div class="sc-status-line"><span>Última sincronização<small id="scLast">Agora</small></span><b class="sc-pill ok">Ativo</b></div></section>
<section class="sc-card wide"><h2>${icon('wallet')} Pagamentos</h2><div class="sc-wallet"><strong>ZumboPay</strong><span>Gateway principal · M-Pesa · e-Mola · B2C</span><div class="sc-actions"><button type="button" id="scTest" class="sc-btn light">${icon('plug')} Testar conexão</button><button type="button" id="scVerify" class="sc-btn light">${icon('wallet-cards')} Verificar wallet</button></div></div><div class="sc-fields"><label>Taxa de transferência (MT)<input id="scFee" type="number" min="0" step="0.01"></label><label>Limite mínimo B2C (MT)<input id="scMin" type="number" min="0" step="0.01"></label><label>Limite máximo B2C (MT)<input id="scMax" type="number" min="0" step="0.01"></label></div></section>
<section class="sc-card"><h2>${icon('landmark')} Carteiras & Payout</h2><label>Wallet operacional<input id="scWalletName"></label><label>Wallet UUID<input id="scWalletUuid"></label><div class="sc-balance"><small>Saldo disponível</small><strong id="scBalance">—</strong></div><label class="sc-toggle">Confirmação antes de enviar<input id="scConfirm" type="checkbox" checked></label><a class="sc-btn light" href="payout.html">${icon('history')} Histórico de operações</a></section>
<section class="sc-card"><h2>${icon('shield')} Segurança</h2><div class="sc-fields"><label>Timeout de sessão (min)<input id="scTimeout" type="number" min="5"></label><label>IPs autorizados<input id="scIps"></label></div><label class="sc-toggle">2FA obrigatório<input id="sc2fa" type="checkbox"></label><label class="sc-toggle">Logs de segurança<input id="scLogs" type="checkbox" checked></label><div class="sc-help">Controles críticos permanecem sujeitos às permissões do backend.</div></section>
<section class="sc-card"><h2>${icon('users-round')} Equipa & Permissões</h2><div class="sc-status-line"><span>Administradores<small>Roles e permissões</small></span><a class="sc-btn light" href="admin.html">Gerir</a></div><label>Role padrão<select id="scRole"><option>admin</option><option>support</option><option>finance</option></select></label><label class="sc-toggle">Convites ativos<input id="scInvites" type="checkbox" checked></label><label class="sc-toggle">Desativar inativos<input id="scInactive" type="checkbox"></label></section>
<section class="sc-card"><h2>${icon('bell')} Notificações</h2>${[['scNEmail','Email'],['scNWhatsapp','WhatsApp'],['scNPayout','Alertas de payout'],['scNPayment','Falhas de pagamento'],['scNKyc','KYC/KYB'],['scNLow','Alertas de saldo baixo']].map(x=>`<label class="sc-toggle">${x[1]}<input id="${x[0]}" type="checkbox" checked></label>`).join('')}</section>
<section class="sc-card"><h2>${icon('network')} Afiliados</h2><div class="sc-fields"><label>Comissão padrão (%)<input id="scAComm" type="number" min="0" step="0.1"></label><label>Bónus (MT)<input id="scABonus" type="number" min="0" step="0.01"></label></div><label>Regra de pagamento<select id="scARule"><option value="monthly">Mensal</option><option value="weekly">Semanal</option><option value="threshold">Por limite</option></select></label><label class="sc-toggle">Programa ativo<input id="scAActive" type="checkbox" checked></label></section>
<section class="sc-card"><h2>${icon('server-cog')} Sistema</h2><div class="sc-status-line"><span>Ambiente<small>Vercel</small></span><b class="sc-pill info">Production</b></div><div class="sc-status-line"><span>Firebase<small>Firestore</small></span><b class="sc-pill ok">Conectado</b></div><div class="sc-status-line"><span>ZumboPay<small>Gateway B2C</small></span><b class="sc-pill ok">Ativo</b></div><div class="sc-status-line"><span>PayGo OS<small>Admin console</small></span><b class="sc-pill info">v3.0</b></div><div class="sc-status-line"><span>API keys / secrets<small>Não editáveis aqui</small></span><b class="sc-pill info">Vercel Env</b></div></section>
</div><div class="sc-save"><span id="scNote">As alterações ficam pendentes até guardar.</span><button id="scSave" class="sc-btn primary" type="submit">${icon('save')} Guardar configurações</button></div></form>`;main.prepend(box);lucide?.createIcons({root:box});
 const cfg={apiKey:'AIzaSyAHxyX5e9O8qQo6Z3VHURgVXhxbxSp0Qh8',authDomain:'paygo-14311.firebaseapp.com',projectId:'paygo-14311',storageBucket:'paygo-14311.firebasestorage.app',messagingSenderId:'208360646277',appId:'1:208360646277:web:aecc57cc0077ae48a52bec'};
 try{const A=await import('https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js'),Au=await import('https://www.gstatic.com/firebasejs/10.7.1/firebase-auth.js'),F=await import('https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js');const app=A.getApps().length?A.getApp():A.initializeApp(cfg),auth=Au.getAuth(app),db=F.getFirestore(app,'paygodb');let admin=null;Au.onAuthStateChanged(auth,async u=>{if(!u)return;const us=await F.getDoc(F.doc(db,'users',u.uid));if(!us.exists()||!['admin','superadmin'].includes(us.data().role))return;admin={u,role:us.data().role};const s=await F.getDoc(F.doc(db,'settings','global'));const d=s.exists()?s.data():{};const map={scName:['platformName','PayGo'],scLogo:['logoUrl',''],scEmail:['supportEmail','suporte@paygo.co.mz'],scPhone:['supportPhone',''],scCurrency:['currency','MZN'],scTimezone:['timezone','Africa/Maputo'],scFee:['payoutFee',0],scMin:['payoutMin',10],scMax:['payoutMax',50000],scWalletName:['walletName',''],scWalletUuid:['walletUuid',''],scConfirm:['payoutConfirmationRequired',true],scTimeout:['sessionTimeout',60],scIps:['allowedIps',''],sc2fa:['twoFactorRequired',false],scLogs:['securityLogs',true],scRole:['defaultAdminRole','admin'],scInvites:['adminInvitesEnabled',true],scInactive:['disableInactiveAdmins',false],scNEmail:['notifyEmail',true],scNWhatsapp:['notifyWhatsapp',true],scNPayout:['notifyPayout',true],scNPayment:['notifyPayment',true],scNKyc:['notifyKyc',true],scNLow:['notifyLowBalance',true],scAComm:['affiliateCommission',3],scABonus:['affiliateBonus',0],scARule:['affiliatePaymentRule','monthly'],scAActive:['affiliateProgramActive',true],scMaintenance:['isMaintenanceMode',false]};Object.entries(map).forEach(([id,[k,v]])=>{const e=document.getElementById(id);if(e)e.type==='checkbox'?e.checked=!!(d[k]??v):e.value=d[k]??v});if(d.updatedAt?.toDate)document.getElementById('scLast').textContent=d.updatedAt.toDate().toLocaleString('pt-MZ')});
 document.getElementById('scForm').onsubmit=async e=>{e.preventDefault();if(!admin)return alert('Sessão administrativa ainda não carregada.');if(scMaintenance.checked&&admin.role!=='superadmin')return alert('Apenas o Super Admin pode ativar a manutenção.');const b=document.getElementById('scSave');b.disabled=true;const v={platformName:scName.value,logoUrl:scLogo.value,supportEmail:scEmail.value,supportPhone:scPhone.value,currency:scCurrency.value,timezone:scTimezone.value,isMaintenanceMode:scMaintenance.checked,payoutFee:+scFee.value||0,payoutMin:+scMin.value||0,payoutMax:+scMax.value||0,walletName:scWalletName.value,walletUuid:scWalletUuid.value,payoutConfirmationRequired:scConfirm.checked,sessionTimeout:+scTimeout.value||60,allowedIps:scIps.value,twoFactorRequired:sc2fa.checked,securityLogs:scLogs.checked,defaultAdminRole:scRole.value,adminInvitesEnabled:scInvites.checked,disableInactiveAdmins:scInactive.checked,notifyEmail:scNEmail.checked,notifyWhatsapp:scNWhatsapp.checked,notifyPayout:scNPayout.checked,notifyPayment:scNPayment.checked,notifyKyc:scNKyc.checked,notifyLowBalance:scNLow.checked,affiliateCommission:+scAComm.value||0,affiliateBonus:+scABonus.value||0,affiliatePaymentRule:scARule.value,affiliateProgramActive:scAActive.checked,paymentGateway:'zumbopay',paysuiteActive:false,updatedBy:admin.u.uid,updatedAt:F.serverTimestamp()};try{await F.setDoc(F.doc(db,'settings','global'),v,{merge:true});scNote.textContent='Guardado com sucesso · '+new Date().toLocaleString('pt-MZ');scSync.textContent='Sincronizado'}catch(err){console.error(err);alert('Erro ao guardar configurações.')}finally{b.disabled=false}};
 document.getElementById('scTest').onclick=async()=>{const b=scTest;b.disabled=true;b.textContent='A verificar...';try{const r=await fetch('/api/admin/zumbopay/payout',{method:'OPTIONS'});scZp.textContent=r.ok?'Conectado':'Backend disponível'}catch(e){scZp.textContent='Verificar backend';scZp.className='sc-pill warn'}finally{b.disabled=false;b.innerHTML=icon('plug')+' Testar conexão';lucide?.createIcons({root:b})}};
 document.getElementById('scVerify').onclick=async()=>{const b=scVerify;b.disabled=true;b.textContent='A verificar...';try{const r=await fetch('/api/admin/zumbopay/payout',{headers:{Authorization:'Bearer '+await admin.u.getIdToken()}});const d=await r.json().catch(()=>({}));scBalance.textContent=r.ok&&d.balance!=null?Number(d.balance).toLocaleString('pt-MZ',{minimumFractionDigits:2})+' MT':r.ok?'Configurada':'Não verificada';scWalletState.textContent=r.ok?'Configurada':'Verificar'}catch(e){scBalance.textContent='Não verificado'}finally{b.disabled=false;b.innerHTML=icon('wallet-cards')+' Verificar wallet';lucide?.createIcons({root:b})}};
 }catch(e){console.error('PayGo settings',e)}
}
function shell(){ensureTheme();buildSidebar();normalizeLayout();buildMobileHeader();if(window.lucide)lucide.createIcons();setTimeout(settingsCenter,100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',shell);else shell();
})();