import crypto from "crypto";
import { getApps, initializeApp, cert } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import { requireZumboAdmin } from "./zumbopay/login.js";

const ZUMBO_URL=(process.env.ZUMBOPAY_API_URL||"https://zumbopay.com/api/public/v1").replace(/\/+$/,'');
const NETSHOP_URL=(process.env.NETSHOP_API_URL||"https://www.netshop.co.mz/api/v1").replace(/\/+$/,'');
const MIN_PAYOUT={netshop:100,zumbopay:10};
const money=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?Math.round(n*100)/100:0};
const method=v=>{const x=String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'');return ['mpesa','emola','mkesh','card'].includes(x)?x:''};
const phone=v=>{const d=String(v||'').replace(/\D/g,'');if(/^258\d{9}$/.test(d))return `+${d}`;if(/^\d{9}$/.test(d))return `+258${d}`;return ''};
const netshopWallet=m=>process.env[`NETSHOP_WALLET_${m.toUpperCase()}`]||process.env.NETSHOP_WALLET_ID||'';
function firebase(){if(!getApps().length){const raw=process.env.FIREBASE_SERVICE_ACCOUNT;if(!raw)throw new Error('FIREBASE_SERVICE_ACCOUNT em falta.');const a=JSON.parse(raw);if(a.private_key)a.private_key=a.private_key.replace(/\\n/g,'\n');initializeApp({credential:cert(a)});}try{return getFirestore(getApps()[0],'paygodb')}catch{return getFirestore()}}
async function json(url,options={}){const r=await fetch(url,{...options,signal:AbortSignal.timeout(30000)});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={message:t||`HTTP ${r.status}`}}if(!r.ok){const e=new Error(String(d?.error?.message||d?.message||d?.error||`HTTP ${r.status}`));e.status=r.status;e.code=d?.error?.code||d?.code||null;throw e}return d?.data??d}
function validate(body,provider){const amount=money(body.amount),m=method(body.method),destination=phone(body.destination||body.phone||body.msisdn),min=MIN_PAYOUT[provider]||10;if(amount<min)throw new Error(`O payout ${provider==='netshop'?'NetShop':'ZumboPay'} não pode ser inferior a ${min.toFixed(2)} MT.`);if(!m||!/^\+258\d{9}$/.test(destination))throw new Error('Método ou número de destino inválido.');return{amount,m,destination}}
async function createZumbo(body){const key=process.env.ZUMBOPAY_API_KEY,merchant=process.env.ZUMBOPAY_MERCHANT_ID;if(!key||!merchant)throw new Error('Credenciais ZumboPay não configuradas.');const {amount,m,destination}=validate(body,'zumbopay');const walletId=String(body.walletId||body.wallet_id||'').trim();if(!walletId)throw new Error('Selecione uma wallet ZumboPay.');const p=await json(`${ZUMBO_URL}/payouts`,{method:'POST',headers:{Authorization:`Bearer ${key}`,'X-Merchant-Id':merchant,'Idempotency-Key':String(body.idempotencyKey||`paygo-${Date.now()}-${crypto.randomBytes(8).toString('hex')}`),Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({wallet_id:walletId,amount,method:m,destination,...(body.notes?{notes:String(body.notes).slice(0,500)}:{})})});return{id:p.id||null,reference:p.reference||null,providerReference:p.provider_reference||null,provider:'zumbopay',method:p.method||m,destination:p.destination||destination,amount:money(p.amount??amount),fee:money(p.fee_amount),currency:p.currency||'MZN',status:String(p.status||'pending').toUpperCase(),walletId}}
async function createNetshop(body){const key=process.env.NETSHOP_API_KEY;if(!key)throw new Error('NETSHOP_API_KEY não configurada.');const {amount,m,destination}=validate(body,'netshop');const walletId=netshopWallet(m);if(!walletId)throw new Error(`Wallet NetShop de ${m} não configurada.`);const reference=String(body.reference||`PG-PAYOUT-${Date.now()}`).trim();const p=await json(`${NETSHOP_URL}/payouts`,{method:'POST',headers:{Authorization:`Bearer ${key}`,'X-Wallet-ID':String(walletId),'Idempotency-Key':String(body.idempotencyKey||`paygo-${reference}-${crypto.randomBytes(6).toString('hex')}`),Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({amount,currency:'MZN',method:m,msisdn:destination,reference})});return{id:p.id||null,reference:p.reference||reference,providerReference:p.provider_reference||p.payout_id||null,provider:'netshop',method:p.method||m,destination:p.msisdn||destination,amount:money(p.amount??amount),fee:money(p.fee||p.fee_amount),currency:p.currency||'MZN',status:String(p.status||'PROCESSING').toUpperCase(),walletId}}
function serialize(doc,provider){const d=doc.data()||{};const c=d.createdAt?.toDate?d.createdAt.toDate().toISOString():d.createdAt||null;return{...d,id:doc.id,provider:d.provider||provider,amount:money(d.amount),createdAt:c,updatedAt:d.updatedAt?.toDate?d.updatedAt.toDate().toISOString():d.updatedAt||c}}
async function history(provider){const db=firebase(),collection=provider==='netshop'?'netshop_payouts':'zumbopay_payouts';try{const s=await db.collection(collection).orderBy('createdAt','desc').limit(200).get();return s.docs.map(d=>serialize(d,provider))}catch{return[]}}
async function persist(provider,payout,body){const db=firebase(),collection=provider==='netshop'?'netshop_payouts':'zumbopay_payouts',id=String(payout.reference||payout.id||`${provider}-${Date.now()}`).replace(/\//g,'_');await db.collection(collection).doc(id).set({...payout,provider,holder:body.holder?String(body.holder).slice(0,160):null,notes:body.notes?String(body.notes).slice(0,500):null,createdAt:new Date(),updatedAt:new Date(),source:'paygo-admin-unified-payout'},{merge:true})}
export default async function handler(req,res){res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS')return res.status(204).end();if(!(await requireZumboAdmin(req)))return res.status(401).json({success:false,error:'Acesso administrativo necessário.'});const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});try{if(req.method==='GET'){const provider=String(req.query?.provider||'all').toLowerCase();if(!['all','netshop','zumbopay'].includes(provider))return res.status(400).json({success:false,error:'Provider inválido.'});const[n,z]=await Promise.all([provider==='all'||provider==='netshop'?history('netshop'):[],provider==='all'||provider==='zumbopay'?history('zumbopay'):[]]);return res.status(200).json({success:true,payouts:[...n,...z].sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))),minPayout:MIN_PAYOUT,providers:{netshop:Boolean(process.env.NETSHOP_API_KEY),zumbopay:Boolean(process.env.ZUMBOPAY_API_KEY)}})}if(req.method!=='POST')return res.status(405).json({success:false,error:'Método não permitido.'});const provider=String(body.provider||'netshop').toLowerCase();if(!['netshop','zumbopay'].includes(provider))return res.status(400).json({success:false,error:'Provider inválido.'});const payout=provider==='zumbopay'?await createZumbo(body):await createNetshop(body);await persist(provider,payout,body);await firebase().collection('admin_audit_logs').add({adminAction:'PAYOUT_CREATED',provider,payoutId:payout.id||null,reference:payout.reference||null,amount:payout.amount,method:payout.method,destination:payout.destination,createdAt:new Date()});return res.status(201).json({success:true,payout})}catch(e){console.error('[PayGo Admin Payout]',e);return res.status(e?.status>=400&&e.status<500?e.status:502).json({success:false,error:e?.message||'Não foi possível processar o payout.',code:e?.code||null})}}
